- hosts: all
  tasks:
  - shell: cat /tmp/test_file.txt
    register: output
  - name: Ansible when variable contains string example
    debug:
      msg: "Equals"
    when: output.stdout.find("world") != -1

