- hosts: servers
  tasks:
    - name: Restart services
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - apache2
        - cron
      loop_control:
        pause: 10
