- hosts: servers
  tasks:
    - debug:
        msg: "{{ ansible_architecture }}"

    - debug:
        msg: "{{ansible_apparmor.status}}"

    - debug: 
        msg: "{{ansible_all_ipv4_addresses}}"

    - debug:
        msg: "{{ansible_all_ipv4_addresses[0]}}"

