---
- hosts: servers
  tasks:
    - name: Copy using the content for inline data
      copy:
        content: '# This file was moved to /etc/other.conf'
        dest: /etc/mine.conf
      become: yes
