---
- hosts: servers
  tasks:
    - name: Update ssh config
      copy:
        src: ssh_config
        dest: /etc/ssh/ssh_config
        owner: root
        group: root
        mode: 0644
        backup: yes
      become: yes

