- hosts: servers
  tasks:
    - name: Add the user 'rsergio' with a specific uid and add it to 'admins'
      user:
        name: rsergio
        comment: Remi Sergio
        uid: 1040
        group: admin
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
      become: yes
