- hosts: servers
  tasks:
    - name: Copy file with owner and permission
      ansible.builtin.copy:
        src: /srv/foo.conf
        dest: /etc/foo.conf
        owner: ubuntu
        group: ubuntu
        mode: u=rw,g=r,o=r
      become: yes

    - name: Create a symbolic link
      ansible.builtin.file:
        src: /etc/foo.conf
        dest: /tmp/foo.conf
        owner: ubuntu
        group: ubuntu
        state: link
